### ISSUE TITLE
Senseiv2 on RGB-NIR 3 meters images

### ISSUE THREAD

**Issue by mauropk** [aliFrancis/SEnSeIv2#3]
Hi, i would be interested in trying Senseiv2 on RGB-NIR images at about 3 meters resolution and i have a few questions. 

Do you think a re-training would be necessary? 

If i were to use the pre-trained weights, what are the steps i should take? Just normalizing/resizing the images and populating the band descriptors with the correct bandwidth values?

**Comment by aliFrancis** [comment]
Hi there!

I think it would be reasonable to try at 3 m/pixel without retraining. It saw some PeruSat-1 images which are around 2 m/pixel if I recall correctly, so it should work okay!

For the descriptors, yes, you should just create them in the same way as they are defined for the other instruments in `senseiv2/constants.py`

As for normalization, it expects physical TOA reflectance values in the standard 0->1 (but in reality with many values above 1 due to strong reflectors, geometry, etc.). In the case of Sentinel-2, that's dividing by 10000, in the case of Landsat 8 it's a bit different because the solar correction must be applied, and it may well be different for your target sensor, but I assume you have a way to retrieve such values.

Would welcome a PR with the new descriptors if you find that it works well, and if you think the instrument you are masking is relevant for other people's work too.

**Comment by aliFrancis** [comment]
Hey @mauropk, how did you get along? Curious to know what the effect was of the higher resolution.
